### ISSUE TITLE
[epic] MVP aka v0.1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/nextjs-tailwind-mdx#1]
When booting a new nextjs based site (e.g. for portaljs setups as well as general sites) I want a starter template that is robust, has the key things I need (but no more) as well as instructions for extending so that I can get started very quickly.

Key features out of the box are:

* Tailwind
* Markdown / MDX support
* Config for some key tweakable items (e.g. the title)

Instructions for:

* Customizing theme
* ...

### Preliminaries

* [x] Why do this and why not reuse something existing **See intro above**
* [ ] Research existing approaches **DONE
  * [ ] https://github.com/timlrx/tailwind-nextjs-starter-blog - excellent but too many batteries included for what we need
  * [ ] e.g. GitHub - https://github.com/mihalik/nextjs-mdx-tailwind-starter - has 3*
  * [ ] Whole bunch of examples for nextjs (each of these does just one thing, we particularly 
 
### Implementation

* [ ] Basic NextJS + tailwind (better than starting with MDX as more basic)
* [ ] Layout
  * [ ] Nav
* [ ] MDX

### Why do this (vs reuse another)

Pros / cons of doing our own nextjs template for tailwind + nextjs (vs e.g. https://github.com/timlrx/tailwind-nextjs-starter-blog)

Pros:

* need this for life itself community, tao site, even standard portal sites. Can’t find something simple that provides this atm (the timlrx one is good but much too complex - we want the simplest and you add things).

Cons: takes time from just doing it (e.g. just create the site)

Pros: just doing it has become a bit time consuming and buggy ...

**Comment by rufuspollock** [comment]
TODO: more use of siteConfig in Layout and Nav.
